shinyproxy:
  apps:
    - id: "asta"
      display-name: "ASTA"
      description: ""
      container-image: "berangered/asta:v1.3"
      container-memory-limit: 4000Mi
      container-cpu-limit: 1000m
      container-memory-request: 2000Mi
      container-cpu-request: 100m

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: asta.lab.sspcloud.fr
